name: Add comment to pull request
on:
  push:
    paths:
      - '**.js'
  pull_request:
    types:
      - opened
    paths:
      - '**.js'

jobs:
  add-frontend-rule-comment:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v1
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          state: open
      - name: Find Comment
        if: steps.findPr.outputs.pr
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ steps.findPr.outputs.pr }}
          comment-author: 'github-actions[bot]'
          body-includes: フロントエンド規約
      - name: Create comment
        if: steps.findPr.outputs.pr && steps.fc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ steps.findPr.outputs.pr }}
          body: |
            ## フロントエンド規約
            - [ ] test
