name: Repository Dispatch Sample

on: repository_dispatch

jobs:
  create-latest-schema-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Event Information
        run: |
          echo "Event is '${{ github.event.action }}'"
          echo "Message is '${{ github.event.client_payload.message }}'"
