name: Deploy vite-project to cloud flare
on:
  push:
    branches:
      - build-js-by-vite
      # - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CLOUD_FLARE_API_TOKEN }}
